name: Create release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "The version of the release to create"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update version in code
        run: |
          sed -i 's/__version__[[:space:]]*=[[:space:]]*"[^"]*"/__version__ = "${{ inputs.version }}"/' terra/__init__.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version to ${{ inputs.version }}"

      - name: Push tag
        run: |
          tag="${{ inputs.version }}"
          message="Release ${{ steps.deploy.outputs.version }}"
          git config user.name "${GITHUB_ACTOR}" && git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          prerelease: true
